// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLasL83sozBVYWey78C-VIIkI_y9Ul_iY',
    appId: '1:75879668080:web:8ba6c824d4f4e7b84f57b5',
    messagingSenderId: '75879668080',
    projectId: 'task-tender',
    authDomain: 'task-tender.firebaseapp.com',
    storageBucket: 'task-tender.appspot.com',
    measurementId: 'G-5WS39C1TR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCZv99qxXr4_JV7T4Ib8H5rwkf5-ZWLU',
    appId: '1:75879668080:android:7db9811a32f7aee04f57b5',
    messagingSenderId: '75879668080',
    projectId: 'task-tender',
    storageBucket: 'task-tender.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKPdFeaIp6V34gb4JM8b_Ohg38nC0K_0',
    appId: '1:75879668080:ios:eafc2fda93fa437d4f57b5',
    messagingSenderId: '75879668080',
    projectId: 'task-tender',
    storageBucket: 'task-tender.appspot.com',
    iosBundleId: 'com.example.taskTender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKPdFeaIp6V34gb4JM8b_Ohg38nC0K_0',
    appId: '1:75879668080:ios:a392e42bb3c3b8424f57b5',
    messagingSenderId: '75879668080',
    projectId: 'task-tender',
    storageBucket: 'task-tender.appspot.com',
    iosBundleId: 'com.example.taskTender.RunnerTests',
  );
}
